config/routes.rb
Betsy::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: "static_pages#home"

  match "/about" => "static_pages#about"
  match "/help" => "static_pages#help"
  match "/contact" => "static_pages#contact"
  match "/signup" => "users#new"
  match "/signin" => "sessions#new"
  match "/signout" => "sessions#destroy", via: :delete

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password
  
  before_save { email.downcase! }
  before_save :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  after_validation { self.errors.messages.delete(:password_digest) }

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update, :index]
  before_filter :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to Betsy"
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile Updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

    def signed_in_user
      store_location
      redirect_to signin_url, notice: "Please sign in." unless signed_in?
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Give full title in browser
  def full_title(page_title)
    base_title = "Store"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user?(user)
    user == current_user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small Built with Ruby on Rails by Donald
  %nav
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path

app/views/layouts/_navbar.html.haml
.navbar
  .navbar-inner
    .brand= link_to "Store", root_path, id: "logo"
    %nav
      %ul.nav.pull-right
        %li= link_to "Help", help_path
        %li= link_to "About", about_path 
        %li= link_to "Contact", contact_path
        - if signed_in?
          %li= link_to "Users", users_path
          %li.dropdown
            %a.dropdown-toggle{ :data => { :toggle => "dropdown" }}
              Account 
              %b.caret
            %ul.dropdown-menu
              %li= link_to "Profile", current_user
              %li= link_to "Settings", edit_user_path(current_user)
              %li.divider
              %li= link_to "Sign out", signout_path, method: "delete"
        - else
          %li= link_to "Sign in", signin_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= full_title(yield(:title))  
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags

  %body
    %br
    .container
      = render partial: "layouts/navbar"

      - flash.each do |key, value|
        .alert.box{ class: "alert-#{key}"}
          %strong
            = value
          %a.close{ :data => { :dismiss => "alert" }}x
          
      
      = yield

      = render partial: "layouts/footer"

      = debug(params) if Rails.env.development?

app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  %ul.alert.alert-error.alert-block.unstyled
    %h4.text-left= "Form contains #{pluralize(@user.errors.count, "error")}"
    %br
    - @user.errors.full_messages.each do |error|
      %li.text-left= error

app/views/static_pages/about.html.haml
= provide(:title, "About")
%h1 About
%p Created by Donald McKendrick

app/views/static_pages/contact.html.haml
= provide(:title, "Contact")
%h1 Contact
%p Donald is in charge around here. He can be contacted at dddmckendrick@gmail.com

app/views/static_pages/help.html.haml
= provide(:title, "Help")
%h1 Help
%p Coming soon.

app/views/static_pages/home.html.haml
.hero-unit.center
  %h1 Welcome to the store
  %h2 The place for hand-made goods

  = link_to "Sign Up Now", signup_path, class: "btn btn-inverse btn-large"

%hr
.container-marketing
  .row
    .span4.offset1.center
      %h4 Shoppers
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut blandit libero. Suspendisse lobortis dapibus sodales. Aliquam erat volutpat. Aliquam quis rhoncus magna, et gravida eros. Praesent leo quam, feugiat a mi in, pellentesque cursus libero. Fusce aliquet vestibulum dignissim. Fusce in tortor fringilla, tempus nisi ac, blandit diam.
      = link_to "Browse", "#", class: "btn btn-inverse"

    .span4.offset2.center
      %h4 Creators
      %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ut blandit libero. Suspendisse lobortis dapibus sodales. Aliquam erat volutpat. Aliquam quis rhoncus magna, et gravida eros. Praesent leo quam, feugiat a mi in, pellentesque cursus libero. Fusce aliquet vestibulum dignissim. Fusce in tortor fringilla, tempus nisi ac, blandit diam.
      = link_to "Sign Up", signup_path, class: "btn btn-inverse"

app/views/users/edit.html.haml
= provide(:title, "Edit user")

.row
  .span4.offset4.center
    = form_for(@user) do |f|
      %h1 Update your profile
      
      = render partial: "shared/error_messages"

      = f.text_field :name, placeholder: "Name"
      = f.text_field :email, placeholder: "Email"      
      = f.password_field :password, placeholder: "Password"
      = f.password_field :password_confirmation, placeholder: "Password Confirmation"
      = f.submit "Save changes", class: "btn btn-inverse"

    = gravatar_for @user

    .text-left= link_to "change", "http://gravatar.com/emails"

app/views/users/index.html.haml
= provide(:title, "All users")
%h1 All users


.container
  .row  
    %ul.unstyled.index
      - @users.each do |user|
        .span3
          %li
            = gravatar_for user, size: 52
            %p= link_to user.name, user_path(user)

  .center= will_paginate

app/views/users/new.html.haml
= provide(:title, "Sign Up")

.row
  .span4.offset4.center
    = form_for(@user) do |f|
      %h1 Sign Up
      
      = render partial: "shared/error_messages"

      = f.text_field :name, placeholder: "Name"
      = f.text_field :email, placeholder: "Email"      
      = f.password_field :password, placeholder: "Password"
      = f.password_field :password_confirmation, placeholder: "Password Confirmation"
      = f.submit "Create my account", class: "btn btn-inverse" 
    

app/views/users/show.html.haml
= provide(:title, @user.name)

.row
  %aside.span4
    %section
      %h1= gravatar_for(@user) + "#{@user.name}"
      = @user.email
    